# Generated by Django 5.1.3 on 2024-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=80)),
                ('account_no', models.BigIntegerField()),
                ('balance', models.IntegerField()),
                ('pin', models.CharField(max_length=4)),
                ('photo', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
