# Generated by Django 5.1.3 on 2024-12-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bankaccount_balance_alter_bankaccount_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
